# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests Automatisés

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repository
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: pip install -r requirements.txt || echo "Pas de requirements.txt, installation ignorée"

      - name: Vérifier la structure des fichiers
        run: ls -R  # Vérifier que `tests/test_converter.py` est bien là

      - name: Exécuter les tests
        run: python -m unittest discover tests/
